### ISSUE TITLE
java.lang.ClassNotFoundException: org.apache.catalina.filters.CorsFilter after clean build / launch

### ISSUE THREAD

**Issue by ssadedin** [kiss-web/Kiss#1]
I did the following on my Mac:

```
git clone https://github.com/kiss-web/Kiss.git
cd Kiss/
gradle javadoc
gradle appRun
```

But the server reports the following exception:

```
10:27:55 WARN  
java.lang.ClassNotFoundException: org.apache.catalina.filters.CorsFilter
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_131]
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335) ~[na:1.8.0_131]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_131]
...
```

And then accessing the page results in:

```
HTTP ERROR: 503

Problem accessing /Kiss/. Reason:

    Service Unavailable
```

For reference:

```
gradle --version

------------------------------------------------------------
Gradle 4.3.1
------------------------------------------------------------

Build time:   2017-11-08 08:59:45 UTC
Revision:     e4f4804807ef7c2829da51877861ff06e07e006d

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_131 (Azul Systems, Inc. 25.131-b11)
OS:           Mac OS X 10.11.6 x86_64
```

**Comment by blakemcbride** [comment]
Hi Simon,

The "gradle appRun" was something I used very early.  Later, I switched to a split development environment (one serving up the front-end and the other serving up the back-end).  This allowed me to edit both the front-end source code and back-end source code without any re-deploys, file copies, or server reboots.  This is described in the manual in sections 4.1.1 and 4.2.

The "gradle appRun" was good as a quick check but it wasn't good for development or production.  I added a file to allow the split development (web.xml).  If you delete all occurrences of that file (web.xml), 'gradle appRun' will work.  But, you should restore web.xml for normal development.

Thanks for the feedback.  I will do something to smooth this out.

Please let me know if this solved the problem.

Thanks.

Blake

**Comment by blakemcbride** [comment]
Also, don't forget that the system won't run at all without a database.  It requires this for user authentication.  It's documented in section 2.4.

**Comment by blakemcbride** [comment]
I have updated the code to make "gradle appRun" work, and I updated the documentation to make things clearer.

**Comment by blakemcbride** [comment]
Hi.  Just FYI, since you first downloaded the system I have resolved the startup kinks, better documented how it works and created a quick-start checklist.  Thanks for the feedback!

**Comment by ssadedin** [comment]
Thanks! I see you have done heaps of work on the documentation. I will revisit and try it again when I have a few minutes to set up a database to get it working properly.

**Comment by blakemcbride** [comment]
Thanks.  I also did a bunch of work on the system to be sure it flows easily in all environments.  Please feel free with any questions!  blake1024@gmail.com
